### ISSUE TITLE
controller / enable testing

### ISSUE THREAD

**Issue by jeremybirch** [TinyTapeout/tt-multiplexer#1]
As we have no manufacturing testing of these chips, particularly the user portion, it would be useful to at least be able to show that the enable shift chain is working as expected. 
One simple way to do this would be to bring the end of the shift chain back out to a pad (during reset) so that we can see that if we shift N+1 times (where N is the number of user blocks) that the enable comes out at the right time. That we we would at least have some faith that the shift was working correctly, and would be able to characterise it, etc

**Comment by smunaut** [comment]
There is no shift chain whatsoever ...

**Comment by mattvenn** [comment]
I don't really understand the way designs are enabled: https://github.com/TinyTapeout/tt03-multiplexer/blob/9000062560129114836de59857dd23912760cbb5/proto/tt_ctrl.v#L90

**Comment by smunaut** [comment]
It's an asynchronous counter.
Depending on the number of pulses, it counts up from 0 to 1023.
Then bit [9:5] are used to decode active row, and bit [4:0] to decode the active colum.
Decoding it done combinatorially.

**Comment by jeremybirch** [comment]
Ok - sorry I thought it was shifting on the clock pulses. Any way we can
have visibility on the pins of it decoding so that we know at least that
bit is working?

**Comment by jeremybirch** [comment]
Alternatively if it is counting pulses / why not just drive those row and
column components in from the pins and latch them on the trailing edge of
reset?!

**Comment by smunaut** [comment]
This was discussed in the call.

Because then you need an external mux for 10 IO lines which is really annoying to deal with in a lot of cases depending on what you want to connect there.

An external uC can take care of sending the pulse with no problem.
Or if the caravel uC works, it can fulfill that function itself simply with 3 external straps ( and I took care to make an easy to strap pinout)

**Comment by jeremybirch** [comment]
Ok how about use 1 extra pin and shift in the row and column bits ie takes
around 16 cycles rather than 200+ and eliminates the decode?

**Comment by jeremybirch** [comment]
an advantage of this is that with  few extra bits in the shift chain you could also configure the IO’s for the given design (ie saying which of the bidirectional pins are configures to input/output/inout) rather than having that as a bus that has to run to every user design. Possibly less flexible than having each of the bidi pins individually configurable from every design on the fly, but I think a lot simpler and demands less wiring resource. Any other configuration specific to the design could also be done this way

**Comment by WallieEverest** [comment]
Would someone confirm there are 37 MPRJ_IO pins to work with? It seems we have a few unexplored options. A simple solution would be best. We have student users.
Somewhat related topic: Which of the +1.8V power domains connect to our TT2 projects? VCCHIB, VCCD, VCCD1, or VCCD2? Can we isolate the RISC-V and/or the selection logic from the projects? Will the remaining chip work if user space is powered off?

**Comment by mattvenn** [comment]
Yes, but as mentioned in the other issue, not all are easily usable.
Yes we're trying for simplicity and ensuring it works.
I can never remember the power domains, take a look at the caravel datasheet. We'll be using the first digital supply domain.
