### ISSUE TITLE
Schematic link for tt_asw_1v8 is wrong

### ISSUE THREAD

**Issue by FangameEmpire** [TinyTapeout/tt-multiplexer#14]
The schematic viewer URL points to
`https://github.com/TinyTapeout/tt-multiplexer/blob/main/tt_asw_1v8/xschem/tt_asw_1v8.sch`
when it should point to 
`https://github.com/TinyTapeout/tt-multiplexer/blob/main/asw/tt_asw_1v8/xschem/tt_asw_1v8.sch`

The 3.3V version works though.

**Comment by urish** [comment]
Thanks for reporting! where is it linked from?

**Comment by FangameEmpire** [comment]
The link is at the top of https://github.com/TinyTapeout/tt-multiplexer/blob/main/asw/tt_asw_1v8/README.md
