### ISSUE TITLE
Consider changing BDIR to simple I/O

### ISSUE THREAD

**Issue by WallieEverest** [TinyTapeout/tt-multiplexer#2]
Looking at the Caravel Harness docs again, we might want to tailor our mux decisions.

https://caravel-harness.readthedocs.io/en/latest/supplementary-figures.html

It would be nice to have a static configuration of the RISC-V flash for all the TT3 projects, something with a consistent I/O configuration.
With MPRJ_IO(36:0) available, why are we multiplexing our project user I/O? (I forget the reason for the BDIR.) Could we have { clk, rst_n, io_in(15:0), io_out(15:0) } for the user projects, and { select_spi[2:0] } for management?  io_oeb(15:0) would be a bonus.

**Comment by mattvenn** [comment]
we'll be defaulting the IOs to a hopefully working setting. Maybe we can avoid the need of flash entirely.
Not all MPRJ_IO is available. Particularly 0 - 4 are used for the flash interface. I've never tried using 0 - 7 as they are all dual use pins.
